baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Echos After Dark'
theme = 'massively'

[params]
  backgroundPath = "images/background.jpg"

[caches]
  [caches.images]
    dir = ':cacheDir/images'